### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by Nixa001**
Add dark mode feature 

#To Do : improve button display on mobile

### CODE REVIEW

**Comment by Nixa001** [comment]
#To do: improve button display on mobile

**Review by Pascal1812 — APPROVED** [review]
Great Nico, thanks a lot for adding the Dark mod future 🫡

**Comment by Pascal1812** [comment]
Based on your code, i noticed that you're trying to change the color of the whole body.
I think it should be greater the dark mode button juste changes the color of the container

**Comment by Nixa001** [comment]
No, I haven't changed the code, just replaced the colors with variables to avoid repetition and apply the darkmode colors.

**Comment by Pascal1812** [comment]
Thank you man for adding the Dark mod functionality, it's great and well done 🫡👏

**Pull request merged**
